#!/bin/sh
# search vimb browsing history, and put results into markdown format
# --also remove search engine results
# --also remove duplicates
grep -i "$@" $HOME/.config/vimb/history |grep -v "duckduckgo" | uniq | linkmarkdown.py
