#!/bin/bash
# for copying mpd playlists
# usage copyplaylist playlist destination
# adds number to filename to keep order intact

# if destination directory does not exist, create it
if [ ! -d "$2" ]; then
   mkdir $2
fi

# start file counter at 1
i=1

#echo $1

while read name
do
  echo $name
  #cp ~/Musique/"$name" $2
 # printf "jjj%s\n" "$name" 

 
  # this will add a leading 0 to numbers under 9 (01, 02 etc)
  # todo:  count number of files, if more than 100 add "00" (001, 002, etc)
  if [ $i -le 9 ]
  then
    lead="0"
  else
    lead=""
  fi

  # remove the directory part of the path
  out1=`echo $name |sed 's/^.*\///'`
  
  # destinationpath/  number filename
  out=`printf "%s/%s%s_%s\n" "$2" "$lead" "$i" "$out1"`
  #echo $out
  
  # copy the file
  cp ~/Musique/"$name" "$out"
  
  # increment file counter
  i=`echo "$i + 1" |bc`

# read line from playlist file
done < "$1"
